networks:
  observability:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  user_service_db_data:
    driver: local
  product_service_db_data:
    driver: local
  order_service_db_data:
    driver: local
  rabbitmq_data:
    driver: local
  grafana_data:
    driver: local
  jaeger_data:
    driver: local

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: obs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-observability_db}
      POSTGRES_USER: ${POSTGRES_USER:-obs_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-obs_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d
      - ./infrastructure/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./infrastructure/postgres/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-obs_user} -d ${POSTGRES_DB:-observability_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: obs_rabbitmq
    restart: unless-stopped
    networks:
      observability:
        ipv4_address: 172.20.0.10
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-obs_user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-obs_password}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-observability_cookie}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infrastructure/rabbitmq/config:/etc/rabbitmq
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Go Collector Service
  collector:
    build:
      context: ./golang
      dockerfile: ./cmd/collector/Dockerfile
    container_name: obs_collector
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-obs_user}:${RABBITMQ_PASSWORD:-obs_password}@obs_rabbitmq:5672/${RABBITMQ_VHOST:-/}
      - POSTGRES_URL=postgres://${POSTGRES_USER:-obs_user}:${POSTGRES_PASSWORD:-obs_password}@postgres:5432/${POSTGRES_DB:-observability_db}?sslmode=disable
      - COLLECTOR_BATCH_SIZE=500
      - COLLECTOR_BATCH_TIMEOUT=5s
      - COLLECTOR_WORKER_POOL_SIZE=20
      - COLLECTOR_RETRY_MAX=5
      - COLLECTOR_RETRY_INTERVAL=2s
      - METRICS_PORT=9090
      - HEALTH_CHECK_PORT=8081
      # Redis Configuration
      - REDIS_URL=redis://obs_redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - REDIS_MIN_IDLE=5
      - REDIS_MAX_RETRIES=3
      - REDIS_TTL=1h
    ports:
      - "9090:9090" # Prometheus Metrics
      - "8081:8081" # Health Check
    networks:
      - observability
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Jaeger Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: obs_jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_ENABLED: true
      SPAN_STORAGE_TYPE: memory
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686"
      - "${JAEGER_COLLECTOR_PORT:-14268}:14268"
      - "${JAEGER_COLLECTOR_OTLP_PORT:-4317}:4317"
      - "${JAEGER_COLLECTOR_OTLP_HTTP_PORT:-4318}:4318"
    networks:
      - observability
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:10.2.0
    container_name: obs_grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    networks:
      - observability
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # User Service Database
  user_service_db:
    image: postgres:15-alpine
    container_name: obs_user_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME:-user_service_db}
      POSTGRES_USER: ${USER_SERVICE_DB_USER:-user_service_user}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD:-user_service_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
      - ./infrastructure/user-service/db/init:/docker-entrypoint-initdb.d
    ports:
      - "${USER_SERVICE_DB_PORT:-5434}:5432"
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USER:-user_service_user} -d ${USER_SERVICE_DB_NAME:-user_service_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Redis for Caching (optional but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: obs_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - ./infrastructure/redis/data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - observability
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Order Service Database
  order_service_db:
    image: postgres:15-alpine
    container_name: obs_order_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_DB_NAME:-order_service_db}
      POSTGRES_USER: ${ORDER_SERVICE_DB_USER:-order_service_user}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD:-order_service_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - order_service_db_data:/var/lib/postgresql/data
      - ./infrastructure/order-service/db/init:/docker-entrypoint-initdb.d
    ports:
      - "${ORDER_SERVICE_DB_PORT:-5436}:5432"
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_SERVICE_DB_USER:-order_service_user} -d ${ORDER_SERVICE_DB_NAME:-order_service_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Order Service
  order-service:
    build:
      context: .
      dockerfile: ./services/order-service/Dockerfile
    container_name: obs_order_service
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - order_service_db
      - jaeger
    networks:
      - observability
    environment:
      - NODE_ENV=development
      - PORT=8080
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-obs_user}:${RABBITMQ_PASSWORD:-obs_password}@obs_rabbitmq:5672/${RABBITMQ_VHOST:-/}
      - RABBITMQ_HOSTNAME=obs_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-obs_user}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-obs_password}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
      - DATABASE_URL=postgresql://${ORDER_SERVICE_DB_USER:-order_service_user}:${ORDER_SERVICE_DB_PASSWORD:-order_service_password}@order_service_db:5432/${ORDER_SERVICE_DB_NAME:-order_service_db}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # User Service
  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: obs_user_service
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - user_service_db
      - jaeger
    networks:
      - observability
    environment:
      - NODE_ENV=development
      - PORT=3004
      - RABBITMQ_USER=${RABBITMQ_USER:-obs_user}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-obs_password}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
      - RABBITMQ_HOSTNAME=obs_rabbitmq
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-obs_user}:${RABBITMQ_PASSWORD:-obs_password}@obs_rabbitmq:5672/${RABBITMQ_VHOST:-/}
      - DATABASE_URL=postgresql://${USER_SERVICE_DB_USER:-user_service_user}:${USER_SERVICE_DB_PASSWORD:-user_service_password}@user_service_db:5432/${USER_SERVICE_DB_NAME:-user_service_db}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    ports:
      - "3004:3004"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Product Service Database
  product_service_db:
    image: postgres:15-alpine
    container_name: obs_product_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PRODUCT_SERVICE_DB_NAME:-product_service_db}
      POSTGRES_USER: ${PRODUCT_SERVICE_DB_USER:-product_service_user}
      POSTGRES_PASSWORD: ${PRODUCT_SERVICE_DB_PASSWORD:-product_service_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - product_service_db_data:/var/lib/postgresql/data
      - ./infrastructure/product-service/db/init:/docker-entrypoint-initdb.d
    ports:
      - "${PRODUCT_SERVICE_DB_PORT:-5435}:5432"
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCT_SERVICE_DB_USER:-product_service_user} -d ${PRODUCT_SERVICE_DB_NAME:-product_service_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Product Service
  product-service:
    build:
      context: .
      dockerfile: ./services/product-service/Dockerfile
    container_name: obs_product_service
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - product_service_db
      - jaeger
    networks:
      - observability
    environment:
      - NODE_ENV=development
      - PORT=3003
      - RABBITMQ_USER=${RABBITMQ_USER:-obs_user}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-obs_password}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-/}
      - RABBITMQ_HOSTNAME=obs_rabbitmq
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-obs_user}:${RABBITMQ_PASSWORD:-obs_password}@obs_rabbitmq:5672/${RABBITMQ_VHOST:-/}
      - DATABASE_URL=postgresql://${PRODUCT_SERVICE_DB_USER:-product_service_user}:${PRODUCT_SERVICE_DB_PASSWORD:-product_service_password}@product_service_db:5432/${PRODUCT_SERVICE_DB_NAME:-product_service_db}
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6832
    ports:
      - "3003:3003"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Health Check Service
  health-check:
    build:
      context: ./scripts
      dockerfile: Dockerfile.healthcheck
    container_name: obs_health_check
    restart: "no"
    depends_on:
      - postgres
      - rabbitmq
      - jaeger
      - grafana
      - redis
      - product-service
      - order-service
    networks:
      - observability
