apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: observability_db
    user: obs_user
    secureJsonData:
      password: obs_secure_password_2024
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags:
          - key: 'service.name'
            value: 'service_name'
          - key: 'correlationId'
            value: 'correlation_id'
      nodeGraph:
        enabled: true
      spanBar:
        type: 'Tag'
        tag: 'http.status_code'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'traceID=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: 'standalone'
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0

  - name: JSON API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://localhost:8080
    isDefault: false
    editable: true
    jsonData:
      cachingConfig:
        enabled: true
        ttl: 300
      timeout: 30

  - name: User Service DB
    type: postgres
    access: proxy
    url: user_service_db:5432
    database: user_service_db
    user: user_service_user
    secureJsonData:
      password: user_service_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: true
