global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'product-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['product-service:8082']

  - job_name: 'order-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['order-service:8080']
  
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
