{
 "title": "User Service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=\"user-service\"}[5m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Success & Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"user-service\", code=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"user-service\"}[5m])) * 100",
     "legendFormat": "5xx Errors"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"user-service\", code=~\"4..\"}[5m])) / sum(rate(http_requests_total{job=\"user-service\"}[5m])) * 100",
     "legendFormat": "4xx Errors"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"user-service\", code=~\"2..\"}[5m])) / sum(rate(http_requests_total{job=\"user-service\"}[5m])) * 100",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"obs_user_service\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"obs_user_service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RabbitMQ: Messages Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[5m])) by (channel)",
     "legendFormat": "Published to {{channel}}"
    }
   ]
  }
 ]
}